name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Build Firebase Config
      run: |
        # Create firebase-config.js from template
        cp firebase-config-template.js firebase-config.js
        
        # Replace placeholders with actual secrets (if they exist)
        if [ -n "$FIREBASE_API_KEY" ] && [ "$FIREBASE_API_KEY" != "" ]; then
          sed -i "s/YOUR_API_KEY/$FIREBASE_API_KEY/g" firebase-config.js
          sed -i "s/YOUR_AUTH_DOMAIN/$FIREBASE_AUTH_DOMAIN/g" firebase-config.js
          sed -i "s/YOUR_PROJECT_ID/$FIREBASE_PROJECT_ID/g" firebase-config.js
          sed -i "s/YOUR_STORAGE_BUCKET/$FIREBASE_STORAGE_BUCKET/g" firebase-config.js
          sed -i "s/YOUR_SENDER_ID/$FIREBASE_MESSAGING_SENDER_ID/g" firebase-config.js
          sed -i "s/YOUR_APP_ID/$FIREBASE_APP_ID/g" firebase-config.js
          sed -i "s/YOUR_MEASUREMENT_ID/$FIREBASE_MEASUREMENT_ID/g" firebase-config.js
        fi
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
